---
# This workflow template runs:
#   - a tox container with tests
#   - a service container (eg. a database) to be used by tox tests.

name: Test

# Github token permissions.
permissions: {}

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-tox-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: python:3.12

    # This stanza deploys a service container with
    #   the "rabbit" hostname. This is commented
    #   to save build time. Uncomment it if you need
    #   it!
    # services:
    #   rabbit:
    #    image: rabbitmq:3-management
    #      ports:
    #      - 5672:5672

    # ...then run the tox jobs referencing
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #  IMPORTANT!! By default `actions/checkout` just checkouts HEAD, so if you want
    #              to checkout tags and branches too (eg. to auto-version your deployments)
    #              you need to pass the `fetch-depth: 0` option. eg
    #
    #              uses: actions/checkout@v2
    #              with:
    #                fetch-depth: 0
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: >-
        Configure git safe directory, because GITHUB_WORKSPACE
        is owned by a different user than the one running the
        tests.
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Run tests.
      run: |
        pip3 install uv
        pip3 install tox-uv
        tox
